//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHCHUYENBAY
    {
        public int STT { get; set; }
        public Nullable<int> MaCB { get; set; }
        public string MaSanBayDi { get; set; }
        public string MaSanBayDen { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
        public Nullable<int> SoLuongGheTrong { get; set; }
        public Nullable<int> SoLuongGheDat { get; set; }
    }
}
