//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHBAY()
        {
            this.DANHSACHCHUYENBAY = new HashSet<DANHSACHCHUYENBAY>();
        }
    
        public string MaCB { get; set; }
        public string MaSanBayDi { get; set; }
        public string MaSanBayDen { get; set; }
        public Nullable<System.DateTime> NgayGio { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBay { get; set; }
        public Nullable<int> SoLuongGheHang1 { get; set; }
        public Nullable<int> SoLuongGheHang2 { get; set; }
        public string MaSBTrungGian { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHCHUYENBAY> DANHSACHCHUYENBAY { get; set; }
        public virtual SANBAY SANBAY { get; set; }
        public virtual SANBAYTRUNGGIAN SANBAYTRUNGGIAN { get; set; }
    }
}
