//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHBAY
    {
        public string MaCB { get; set; }
        public string MaSanBayDi { get; set; }
        public string MaSanBayDen { get; set; }
        public Nullable<System.DateTime> NgayGio { get; set; }
        public string ThoiGianBay { get; set; }
        public Nullable<int> SoLuongGheHang1 { get; set; }
        public Nullable<int> SoLuongGheHang2 { get; set; }
        public string MaSBTrungGian { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual SANBAY SANBAY { get; set; }
        public virtual SANBAY SANBAY1 { get; set; }
    }
}
