//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDATVE
    {
        public string CMND { get; set; }
<<<<<<< HEAD
        public Nullable<int> STT { get; set; }
=======
>>>>>>> ab841a8cbe284e75c92f99ca18b6ce83f8c20180
        public string MaCB { get; set; }
        public string TenHanhKhach { get; set; }
        public string DienThoai { get; set; }
        public string MaLoai { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual LOAIVE LOAIVE { get; set; }
    }
}
