//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLVeMayBayEntities : DbContext
    {
        public QLVeMayBayEntities()
            : base("name=QLVeMayBayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaiDat> CaiDat { get; set; }
        public virtual DbSet<CHUYENBAY> CHUYENBAY { get; set; }
        public virtual DbSet<DANHSACHCHUYENBAY> DANHSACHCHUYENBAY { get; set; }
        public virtual DbSet<LICHBAY> LICHBAY { get; set; }
        public virtual DbSet<LOAIVE> LOAIVE { get; set; }
        public virtual DbSet<PHIEUDATVE> PHIEUDATVE { get; set; }
        public virtual DbSet<SANBAY> SANBAY { get; set; }
        public virtual DbSet<SANBAYTRUNGGIAN> SANBAYTRUNGGIAN { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
<<<<<<< HEAD
=======
        public virtual DbSet<LICHBAY> LICHBAY { get; set; }
>>>>>>> ab841a8cbe284e75c92f99ca18b6ce83f8c20180
    }
}
