//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANBAYTRUNGGIAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANBAYTRUNGGIAN()
        {
            this.LICHBAY = new HashSet<LICHBAY>();
        }
    
        public string MaSBTrungGian { get; set; }
        public string MaCB { get; set; }
        public string TenSB { get; set; }
        public Nullable<System.TimeSpan> ThoiGianDung { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHBAY> LICHBAY { get; set; }
    }
}
