//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAYDOIQUYDINH
    {
        public int STT { get; set; }
        public Nullable<int> SLSanBay { get; set; }
        public string TGBayToiThieu { get; set; }
        public Nullable<int> SoSBTGToiDa { get; set; }
        public Nullable<int> TGDungToiThieu { get; set; }
        public Nullable<int> TGDungToiDa { get; set; }
    }
}
